export interface GridCategory {
  name: string;
  words: string[];
}

export const GRID_DATA: Record<string, Record<string, string[]>> = {
  en: {
    'ANIMALS': ['BEAR', 'CAT', 'DOG', 'EAGLE', 'FISH', 'GOAT', 'HORSE', 'IGUANA', 'JAGUAR', 'KANGAROO', 'LION', 'MONKEY', 'NEWT', 'OWL', 'PIG', 'QUAIL', 'RAT', 'SNAKE', 'TIGER', 'URCHIN', 'VULTURE', 'WOLF', 'XRAY', 'YAK', 'ZEBRA'],
    'FRUITS': ['APPLE', 'BANANA', 'CHERRY', 'DATE', 'ELDERBERRY', 'FIG', 'GRAPE', 'HONEYDEW', 'KIWI', 'LEMON', 'MANGO', 'NECTARINE', 'ORANGE', 'PEACH', 'QUINCE', 'RASPBERRY', 'STRAWBERRY', 'TANGERINE', 'UGLI', 'WATERMELON'],
    'COUNTRIES': ['ARGENTINA', 'BRAZIL', 'CANADA', 'DENMARK', 'EGYPT', 'FRANCE', 'GERMANY', 'HUNGARY', 'INDIA', 'JAPAN', 'KENYA', 'LAOS', 'MEXICO', 'NORWAY', 'OMAN', 'PERU', 'QATAR', 'RUSSIA', 'SPAIN', 'TURKEY', 'UGANDA', 'VIETNAM', 'WALES', 'YEMEN', 'ZAMBIA'],
    'COLORS': ['AMBER', 'BLACK', 'CYAN', 'DENIM', 'EMERALD', 'FUCHSIA', 'GOLD', 'HAZEL', 'INDIGO', 'JADE', 'KHAKI', 'LILAC', 'MAGENTA', 'NAVY', 'OLIVE', 'PINK', 'QUARTZ', 'RED', 'SILVER', 'TEAL', 'UMBER', 'VIOLET', 'WHITE', 'YELLOW'],
    'JOBS': ['ACTOR', 'BAKER', 'CHEF', 'DOCTOR', 'ENGINEER', 'FARMER', 'GUARD', 'HUNTER', 'JUDGE', 'LAWYER', 'MINER', 'NURSE', 'PILOT', 'RANGER', 'SAILOR', 'TEACHER', 'USHER', 'VET', 'WAITER', 'WRITER'],
    'CLOTHING': ['APRON', 'BELT', 'COAT', 'DRESS', 'EARRING', 'FUR', 'GLOVES', 'HAT', 'JACKET', 'KILT', 'LEGGINGS', 'MITTENS', 'NECKTIE', 'OVERALLS', 'PANTS', 'QUILT', 'ROBE', 'SCARF', 'TIE', 'UNDERWEAR', 'VEST', 'WATCH', 'ZIPPER'],
    'SPORTS': ['ARCHERY', 'BASEBALL', 'CRICKET', 'DIVING', 'FENCING', 'GOLF', 'HOCKEY', 'JUDO', 'KARATE', 'LACROSSE', 'MMA', 'NETBALL', 'POLO', 'QUIDDITCH', 'RUGBY', 'SOCCER', 'TENNIS', 'VOLLEYBALL', 'WRESTLING', 'YOGA']
  },
  es: {
    'ANIMALES': ['AGUILA', 'BALLENA', 'CABALLO', 'DELFIN', 'ELEFANTE', 'FOCA', 'GATO', 'HIENA', 'IGUANA', 'JIRAFA', 'KOALA', 'LEON', 'MONO', 'NUTRIA', 'OSO', 'PERRO', 'QUETZAL', 'RATA', 'SERPIENTE', 'TIGRE', 'URRACA', 'VACA', 'WOMBAT', 'YEGUA', 'ZORRO'],
    'FRUTAS': ['ARANDANO', 'BANANA', 'CEREZA', 'DURAZNO', 'FRAMBUESA', 'GRANADA', 'HIGO', 'KIWI', 'LIMA', 'MANZANA', 'NARANJA', 'PERA', 'QUINOTO', 'SANDIA', 'UVA', 'ZARZAMORA'],
    'PAISES': ['ALEMANIA', 'BRASIL', 'CANADA', 'DINAMARCA', 'ESPAÑA', 'FRANCIA', 'GRECIA', 'HUNGRIA', 'INDIA', 'JAPON', 'KENIA', 'LAOS', 'MEXICO', 'NORUEGA', 'OMAN', 'PERU', 'QATAR', 'RUSIA', 'SUECIA', 'TURQUIA', 'URUGUAY', 'VENEZUELA', 'YEMEN', 'ZAMBIA'],
    'COLORES': ['AMARILLO', 'BLANCO', 'CYAN', 'DORADO', 'ESMERALDA', 'FUCSIA', 'GRIS', 'INDIGO', 'JADE', 'KAKI', 'LILA', 'MAGENTA', 'NEGRO', 'ORO', 'PLATA', 'ROJO', 'SALMON', 'TURQUESA', 'VERDE', 'VIOLETA', 'ZAFIRO'],
    'PROFESION': ['ACTOR', 'BOMBERO', 'COCINERO', 'DOCTOR', 'ELECTRICISTA', 'FARMACEUTICO', 'GERENTE', 'HERRERO', 'INGENIERO', 'JUEZ', 'KINESIOLOGO', 'LIMPIADOR', 'MAESTRO', 'NIÑERA', 'OBRERO', 'PILOTO', 'QUIMICO', 'REPARTIDOR', 'SOLDADO', 'TAXISTA', 'VETERINARIO', 'ZAPATERO'],
    'ROPA': ['ABRIGO', 'BUFANDA', 'CAMISA', 'DELANTAL', 'FALDA', 'GORRO', 'IMPERMEABLE', 'JERSEY', 'KIMONO', 'LENCERIA', 'MEDIAS', 'PANTALON', 'QUIJOTE', 'ROPA', 'SANDALIA', 'TRAJE', 'UNIFORME', 'VESTIDO', 'ZAPATO'],
    'DEPORTES': ['ATLETISMO', 'BALONCESTO', 'CICLISMO', 'DARTS', 'ESGRIMA', 'FUTBOL', 'GOLF', 'HOCKEY', 'JUDO', 'KARATE', 'LUCHA', 'MOTOCICLISMO', 'NATACION', 'POLO', 'RUGBY', 'SURF', 'TENIS', 'VOLEIBOL', 'WATERPOLO', 'YOGA']
  },
  fr: {
    'ANIMAUX': ['AIGLE', 'BALEINE', 'CHAT', 'DAUPHIN', 'ELEPHANT', 'FAON', 'GIRAFE', 'HIBOU', 'IGUANE', 'JAGUAR', 'KOALA', 'LION', 'MOUTON', 'NARVAL', 'OURS', 'PANDA', 'QUOKKA', 'RAT', 'SERPENT', 'TIGRE', 'VACHE', 'WAPITI', 'YAK', 'ZEBRE'],
    'FRUITS': ['ANANAS', 'BANANE', 'CERISE', 'DATTE', 'FRAISE', 'GRENADE', 'HUILE', 'KIWI', 'LIME', 'MANGUE', 'NECTARINE', 'ORANGE', 'POMME', 'RAISIN', 'TOMATE'],
    'PAYS': ['ALLEMAGNE', 'BELGIQUE', 'CANADA', 'DANEMARK', 'ESPAGNE', 'FRANCE', 'GRECE', 'HONGRIE', 'INDE', 'JAPON', 'KENYA', 'LAOS', 'MAROC', 'NORVEGE', 'OMAN', 'PEROU', 'QATAR', 'RUSSIE', 'SUISSE', 'TURQUIE', 'URUGUAY', 'VIETNAM', 'YEMEN', 'ZAMBIE'],
    'COULEURS': ['ARGENT', 'BLEU', 'CYAN', 'DORE', 'EBERLU', 'FUCHSIA', 'GRIS', 'INDIGO', 'JAUNE', 'KAKI', 'LILAS', 'MAGENTA', 'NOIR', 'ORANGE', 'POURPRE', 'ROUGE', 'SAFRAN', 'TURQUOISE', 'VERT', 'VIOLET'],
    'METIERS': ['ACTEUR', 'BOULANGER', 'CUISINIER', 'DOCTEUR', 'ECRIVAIN', 'FACTEUR', 'GARDIEN', 'HUISSIER', 'INFIRMIER', 'JUGE', 'KINE', 'LIVREUR', 'MECANICIEN', 'NOTAIRE', 'OUVRIER', 'PILOTE', 'QUINCAILLIER', 'REDACTEUR', 'SOLDAT', 'TAILLEUR', 'VENDEUR'],
    'VETEMENTS': ['ANORAK', 'BLOUSON', 'CHEMISE', 'DENTELLE', 'ECHARPE', 'FOULARD', 'GANT', 'HABIT', 'IMPER', 'JEAN', 'KIMONO', 'LINGERIE', 'MANTEAU', 'NOEUD', 'PANTALON', 'ROBE', 'SHORT', 'TUNIQUE', 'UNIFORME', 'VESTE'],
    'SPORTS': ['ATHLETISME', 'BOXE', 'CYCLISME', 'DANSE', 'ESCRIME', 'FOOTBALL', 'GOLF', 'HANDBALL', 'JUDO', 'KARATE', 'LUTTE', 'MOTOCROSS', 'NATATION', 'POLO', 'RUGBY', 'SKI', 'TENNIS', 'VOILE', 'WATERPOLO', 'YOGA']
  },
  de: {
    'TIERE': ['ADLER', 'BAER', 'CHAMAALEON', 'DACHS', 'ELEFANT', 'FUCHS', 'GIRAFFE', 'HASE', 'IGEL', 'JAGUAR', 'KATZE', 'LOEWE', 'MAUS', 'NASHORN', 'OCHSE', 'PFERD', 'QUALLE', 'RATTE', 'SCHLANGE', 'TIGER', 'UHU', 'VOGEL', 'WOLF', 'YAK', 'ZEBRA'],
    'FRUECHTE': ['APFEL', 'BANANE', 'CRANBERRY', 'DATTEL', 'ERDBEERE', 'FEIGE', 'GRAPEFRUIT', 'HIMBEERE', 'INGWER', 'JOHANNISBEERE', 'KIRSCHE', 'LIMETTE', 'MANGO', 'NEKTARINE', 'ORANGE', 'PFLAUME', 'QUITTE', 'RHABARBER', 'STACHELBEERE', 'TRAUBE', 'WASSERMELONE', 'ZITRONE'],
    'LAENDER': ['ARGENTINIEN', 'BELGIEN', 'CHINA', 'DAENEMARK', 'ENGLAND', 'FRANKREICH', 'GRIECHENLAND', 'HOLLAND', 'INDIEN', 'JAPAN', 'KANADA', 'LETTLAND', 'MEXIKO', 'NORWEGEN', 'OMAN', 'POLEN', 'KATAR', 'RUSSLAND', 'SPANIEN', 'TUERKEI', 'UNGARN', 'VIETNAM', 'WALES', 'JEMEN', 'ZYPERN'],
    'FARBEN': ['AZUR', 'BLAU', 'CYAN', 'DUNKELBLAU', 'ELFENBEIN', 'FLIEDER', 'GRUEN', 'HELLBLAU', 'INDIGO', 'JADE', 'KAKI', 'LILA', 'MAGENTA', 'NEONGELB', 'ORANGE', 'PINK', 'ROT', 'SCHWARZ', 'TUERKIS', 'VIOLETT', 'WEISS', 'ZITRONENGELB'],
    'BERUFE': ['ARZT', 'BAECKER', 'CHEMIKER', 'DETEKTIV', 'ELEKTRIKER', 'FISCHER', 'GAERTNER', 'HAENDLER', 'INGENIEUR', 'JOURNALIST', 'KOCH', 'LEHRER', 'MALER', 'NOTAR', 'OPTIKER', 'PILOT', 'RICHTER', 'SOLDAT', 'TIERARZT', 'UHRMACHER', 'VERKAEUFER', 'WEBER', 'ZAHNARZT'],
    'KLEIDUNG': ['ANZUG', 'BLUSE', 'CAPE', 'DIRNDL', 'FÄUSTLING', 'GUERTEL', 'HEMD', 'JACKE', 'KLEID', 'LEDERHOSE', 'MANTEL', 'NACHTHEMD', 'OVERALL', 'PULLOVER', 'ROCK', 'SCHAL', 'TRIKOT', 'UNTERHOSE', 'WESTE'],
    'SPORT': ['ANGELN', 'BOXEN', 'CRICKET', 'DARTS', 'EISHOCKEY', 'FUSSBALL', 'GOLF', 'HANDBALL', 'JUDO', 'KARATE', 'LAUFEN', 'MOTORSPORT', 'NETBALL', 'POLO', 'RADSPORT', 'SCHWIMMEN', 'TENNIS', 'VOLLEYBALL', 'WANDERN', 'YOGA']
  },
  it: {
    'ANIMALI': ['AQUILA', 'BALENA', 'CANE', 'DELFINO', 'ELEFANTE', 'FOCA', 'GATTO', 'IENA', 'ISTRICE', 'JAGUARO', 'KOALA', 'LEONE', 'LUPO', 'MALIALE', 'NUTRIA', 'ORSO', 'PANTERA', 'QUAGLIA', 'RAGNO', 'SERPENTE', 'TIGRE', 'USIGNOLO', 'VOLPE', 'WOMBAT', 'YAK', 'ZEBRA'],
    'FRUTTA': ['ARANCIA', 'BANANA', 'CILIEGIA', 'DATTERO', 'FICO', 'GELSO', 'KIWI', 'LIMONE', 'MELA', 'NOCE', 'OLIVA', 'PERA', 'RIBES', 'SUSINA', 'UVA', 'ZUCCA'],
    'PAESI': ['ARGENTINA', 'BRASILE', 'CINA', 'DANIMARCA', 'EGITTO', 'FRANCIA', 'GERMANIA', 'INDIA', 'ITALIA', 'JAPONE', 'KENYA', 'LETTONIA', 'MESSICO', 'NORVEGIA', 'OLANDA', 'PERU', 'QATAR', 'RUSSIA', 'SPAGNA', 'TURCHIA', 'UNGHERIA', 'VIETNAM', 'YEMEN', 'ZAMBIA'],
    'COLORI': ['ARANCIONE', 'BIANCO', 'CIANO', 'DORATO', 'EDERA', 'FUCSIA', 'GIALLO', 'INDACO', 'LILLA', 'MAGENTA', 'NERO', 'OCRA', 'PORPORA', 'ROSA', 'SALMONE', 'TURCHESE', 'VERDE', 'VIOLA', 'ZAFFERANO'],
    'MESTIERI': ['ATTORE', 'BARISTA', 'CUOCO', 'DITTORE', 'ELETTRICISTA', 'FALEGNAME', 'GIARDINIERE', 'IDRAULICO', 'INGEGNERE', 'JUDICE', 'LAVORATORE', 'MAESTRO', 'NOTAIO', 'OPERAIO', 'PILOTA', 'QUESTORE', 'REGISTA', 'SARTO', 'TECNICO', 'VIGILE'],
    'VESTITI': ['ABITO', 'BERRETTO', 'CAMICIA', 'DONNA', 'ELMETTO', 'FELPA', 'GIACCA', 'JEANS', 'KIMONO', 'LANA', 'MAGLIA', 'NAPPA', 'OCCHIALI', 'PANTALONI', 'ROBA', 'SCARPA', 'TUTA', 'UNIFORME', 'VESTITO', 'ZAINO'],
    'SPORT': ['ATLETICA', 'BASKET', 'CALCIO', 'DANZA', 'EQUITAZIONE', 'FIORETTO', 'GOLF', 'HOCKEY', 'JUDO', 'KARATE', 'LOTTA', 'MOTOCICLISMO', 'NUOTO', 'PALLAVOLO', 'RUGBY', 'SCHERMA', 'TENNIS', 'VELA', 'WRESTLING', 'YOGA']
  },
  pt: {
    'ANIMAIS': ['AGUIA', 'BALEIA', 'CACHORRO', 'DINOSSAURO', 'ELEFANTE', 'FOCA', 'GATO', 'HIPOPOTAMO', 'IGUANA', 'JACARE', 'KOALA', 'LEAO', 'MACACO', 'NARVAL', 'ONÇA', 'PATO', 'QUATI', 'RATO', 'SAPO', 'TIGRE', 'URSO', 'VACA', 'XAREU', 'ZEBRA'],
    'FRUTAS': ['ABACAXI', 'BANANA', 'CAJU', 'DAMASCO', 'FIGO', 'GOIABA', 'KIWI', 'LARANJA', 'MANGA', 'NECTARINA', 'OITI', 'PERA', 'QUIUI', 'ROMA', 'TANGERINA', 'UVA', 'XIXA'],
    'PAISES': ['ALEMANHA', 'BRASIL', 'CANADA', 'DINAMARCA', 'ESPANHA', 'FRANÇA', 'GRECIA', 'HOLANDA', 'INDIA', 'JAPAO', 'KUWAIT', 'LAOS', 'MEXICO', 'NORUEGA', 'OMAN', 'PORTUGAL', 'QUENIA', 'RUSSIA', 'SUECIA', 'TURQUIA', 'URUGUAI', 'VENEZUELA', 'ZAMBIA'],
    'CORES': ['AMARELO', 'BRANCO', 'CINZA', 'DOURADO', 'ESMERALDA', 'FUCSIA', 'GRENÀ', 'INDIGO', 'LARANJA', 'LILAS', 'MAGENTA', 'NEGRO', 'OLIVA', 'PRATA', 'ROSA', 'TURQUESA', 'VERDE', 'VERMELHO', 'VIOLETA'],
    'PROFISSAO': ['ATOR', 'BOMBEIRO', 'CARPINTEIRO', 'DENTISTA', 'ENGENHEIRO', 'FARMACEUTICO', 'GARÇOM', 'HISTORIADOR', 'JORNALISTA', 'JUIZ', 'MEDICO', 'NUTRICIONISTA', 'OPERARIO', 'PADRE', 'QUIMICO', 'RECEPCIONISTA', 'SOLDADO', 'TAXISTA', 'VENDEDOR', 'ZELADOR'],
    'ROUPAS': ['AGASALHO', 'BERMUDA', 'CALÇA', 'DOULE', 'ESPARTILHO', 'FALDA', 'GORRO', 'IOIO', 'JAQUETA', 'KIMONO', 'LUVA', 'MEIA', 'NOGUEIRA', 'OCULOS', 'PALETO', 'QUIMONO', 'ROUPÃO', 'SAIA', 'TERNO', 'UNIFORME', 'VESTIDO'],
    'ESPORTES': ['ATLETISMO', 'BASQUETE', 'CAPOEIRA', 'DANÇA', 'ESGRIMA', 'FUTEBOL', 'GOLF', 'HANDEBOL', 'JUDO', 'KARATE', 'LUTA', 'MOTOCROSS', 'NATAÇÃO', 'POLO', 'RUGBY', 'SURF', 'TENIS', 'VOLEI', 'XADREZ', 'YOGA']
  }
};
