export const WORDS_BY_LANG: Record<string, string[]> = {
  en: [
    'TIME', 'BOOK', 'WIND', 'FIRE', 'GOLD', 'SAND', 'BLUE', 'HOME',
    'ACTION', 'ADVICE', 'AGENCY', 'ANSWER', 'APPEAL', 'ARTIST', 'ATTACK', 'AUTHOR', 'BANANA', 'BATTLE',
    'BEAUTY', 'BECOME', 'BETTER', 'BOTTLE', 'BOTTOM', 'BRANCH', 'BREATH', 'BRIDGE', 'BRIGHT', 'BROKEN',
    'COMPUTER', 'MOUNTAIN', 'NEGATIVE', 'PRACTICE', 'STRENGTH', 'LANGUAGE', 'BUSINESS', 'QUESTION'
  ],
  es: [
    'VIDA', 'CASA', 'TIEM', 'AZUL', 'LAGO', 'ROSA', 'SOLO', 'VINO',
    'ABUELO', 'ACCION', 'ACEITE', 'ACTIVO', 'ACTUAL', 'ADULTO', 'AFECTO', 'AGENDA', 'AGENTE', 'AGOSTO',
    'AJUSTE', 'ALARMA', 'ALCALD', 'ALEGRE', 'ALEJAR', 'ALERTA', 'ALTURA', 'ALUMNO', 'AMABLE', 'AMARGO',
    'ESTUDIAR', 'PERSONAS', 'TRABAJAR', 'PALABRAS', 'NEGOCIOS', 'ESCRITOR', 'GOBIERNO', 'PROYECTO'
  ],
  fr: [
    'JOUR', 'BLEU', 'CHAT', 'LOUP', 'MAIN', 'NOIR', 'ROSE', 'VERT',
    'ABORD', 'ABOUT', 'ABSENT', 'ABSOLU', 'ACCENT', 'ACCORD', 'ACHAT', 'ACIDE', 'ACIER', 'ACTEUR',
    'ACTIF', 'ACTION', 'ADIEU', 'ADMET', 'ADORER', 'ADULTE', 'AERIEN', 'AFFARE', 'AGENT', 'AGILE',
    'ETUDIANT', 'FRANCAIS', 'QUESTION', 'TRAVAILL', 'PERSONNE', 'HISTOIRE', 'BOUTIQUE', 'JOURNAL'
  ],
  de: [
    'ZEIT', 'BLAU', 'HAUS', 'WIND', 'GOLD', 'SAND', 'ROSA', 'GRUN',
    'ABEND', 'ABTEI', 'ACHSE', 'ADER', 'ADLER', 'AFFEN', 'AGENT', 'AHORN', 'AKTEN', 'ALARM',
    'COMPUTER', 'SPRACHEN', 'ARBEITEN', 'PERSONEN', 'SOFTWARE', 'GEBAEUDE', 'FREUNDIN', 'ZEITUNGS'
  ],
  it: [
    'MARE', 'SOLE', 'LUCE', 'VINO', 'CASA', 'VITA', 'ROSA', 'NERO',
    'ABATO', 'ABETE', 'ABILE', 'ABISSO', 'ABITO', 'ABUSO', 'ACERO', 'ACETO', 'ACQUA', 'ACUTO',
    'STUDENTE', 'ITALIANO', 'MACCHINA', 'SCRIVERE', 'PROGETTO', 'CITTADIN', 'GIORNALE', 'PUBBLICO'
  ],
  pt: [
    'VIDA', 'CASA', 'MARÉ', 'AZUL', 'ROSA', 'SOLO', 'VINO', 'DOCE',
    'ABAIXO', 'ABALO', 'ABERTO', 'ABISMO', 'ABRIGO', 'ACASO', 'ACAO', 'ACEITO', 'ACERTO', 'ACESSO',
    'TRABALHO', 'ESTUDANT', 'PALAVRAS', 'PROJECTO', 'DINHEIRO', 'HISTORIA', 'GOVERNO', 'PROBLEMA'
  ],
  'pt-BR': [
    'VIDA', 'CASA', 'MARÉ', 'AZUL', 'ROSA', 'SOLO', 'VINO', 'DOCE',
    'ABAIXO', 'ABALO', 'ABERTO', 'ABISMO', 'ABRIGO', 'ACASO', 'ACAO', 'ACEITO', 'ACERTO', 'ACESSO',
    'TRABALHO', 'ESTUDANT', 'PALAVRAS', 'PROJECTO', 'DINHEIRO', 'HISTORIA', 'GOVERNO', 'PROBLEMA'
  ],
  'pt-PT': [
    'VIDA', 'CASA', 'MARÉ', 'AZUL', 'ROSA', 'SOLO', 'VINO', 'DOCE',
    'ABAIXO', 'ABALO', 'ABERTO', 'ABISMO', 'ABRIGO', 'ACASO', 'ACAO', 'ACEITO', 'ACERTO', 'ACESSO',
    'TRABALHO', 'ESTUDANT', 'PALAVRAS', 'PROJECTO', 'DINHEIRO', 'HISTORIA', 'GOVERNO', 'PROBLEMA'
  ]
};
