interface WordLists {
  easy: string[];    // 4 letters
  normal: string[];  // 6 letters
  hard: string[];    // 8 letters
}

export const WORDS_BY_LANG: Record<string, WordLists> = {
  en: {
    easy: [
      'BOOK', 'WIND', 'FIRE', 'GOLD', 'SAND', 'BLUE', 'HOME', 'LION',
      'FROG', 'DUCK', 'FISH', 'BIRD', 'TREE', 'MOON', 'STAR', 'RAIN',
      'SNOW', 'LAKE', 'ROSE', 'LION', 'BEAR', 'WOLF', 'DEER', 'GOAT'
    ],
    normal: [
      'ACTION', 'BOTTLE', 'BRIDGE', 'CANDLE', 'DANGER', 'EAGLE', 'FLOWER', 'GARDEN',
      'HAPPY', 'ISLAND', 'JUNGLE', 'KINDLE', 'LADDER', 'MAGNET', 'NATURE', 'OCEAN',
      'PENCIL', 'QUIET', 'RABBIT', 'SUNSET', 'TICKET', 'UNIVERSE', 'VICTORY', 'WINDOW'
    ],
    hard: [
      'BEAUTIFUL', 'CHRISTMAS', 'DAISY', 'ELEPHANT', 'FIREPLACE', 'GRATITUDE', 'HAPPINESS',
      'ILLUSTRATE', 'JOURNEY', 'KINDNESS', 'LIGHTHOUSE', 'MOUNTAIN', 'NOTEBOOK', 'OUTDOORS',
      'PAINTING', 'QUESTION', 'RAINBOW', 'SUNSHINE', 'TREASURE', 'UMBRELLA', 'VACATION', 'WATERFALL'
    ]
  },
  es: {
    easy: [
      'AGUA', 'CASA', 'FLOR', 'LUNA', 'GATO', 'PERRO', 'MESA', 'SILLA',
      'PATO', 'LAGO', 'ROSA', 'NUBE', 'SILLA', 'MANO', 'PIE', 'SOL',
      'MAR', 'PAN', 'SAL', 'RED', 'LUZ', 'PAZ', 'SAL', 'RED'
    ],
    normal: [
      'ABRIGO', 'BICICLETA', 'CABALLO', 'DORMIR', 'ESCUELA', 'FAMILIA', 'GORILA', 'HABLAR',
      'INVIERNO', 'JARDIN', 'KIWI', 'LIBRO', 'MUSICA', 'NARANJA', 'OCEANO', 'PINTURA',
      'QUESO', 'RELOJ', 'SABADO', 'TECLADO', 'UNIVERSO', 'VIERNES', 'WINDOWS', 'YOGUR'
    ],
    hard: [
      'ALEGRIA', 'BICICLETA', 'CALCULADORA', 'DIFERENTE', 'ESCALERA', 'FOTOGRAFIA', 'GIMNASIO',
      'HABITACION', 'IMPORTANTE', 'JARDINERO', 'KILOMETRO', 'LIMPIEZA', 'MAGNIFICO', 'NARANJADO',
      'ORGANIZAR', 'PELIGROSO', 'QUIMICA', 'RECORDAR', 'SORPRESA', 'TELEFONO', 'ULTIMAMENTE', 'VETERINARIO'
    ]
  },
  fr: {
    easy: [
      'CIEL', 'FLEUR', 'MAIN', 'NUIT', 'PAIN', 'RIRE', 'SOLEIL', 'TERRE',
      'VENT', 'VIE', 'NEIGE', 'LUNE', 'MER', 'SEL', 'THE', 'VERRE',
      'MAIN', 'NEZ', 'OEIL', 'PONT', 'RIZ', 'SANG', 'SEL', 'SUR'
    ],
    normal: [
      'AMOUR', 'BONJOUR', 'CHAISE', 'DORMIR', 'ECOLE', 'FENETRE', 'GARAGE', 'HORLOGE',
      'IMAGINE', 'JARDIN', 'KILO', 'LIVRE', 'MAISON', 'NOEL', 'ORANGE', 'PAPIER',
      'QUATRE', 'ROND', 'SEMAINE', 'TABLE', 'UNIFORME', 'VACANCES', 'WAGON', 'ZERO'
    ],
    hard: [
      'APPAREIL', 'BALANCOIRE', 'CHAMPAGNE', 'DANGEREUX', 'ETOILE', 'FANTASTIQUE', 'GENTILLESSE',
      'HORIZON', 'ILLUSION', 'JALOUSIE', 'KILOMETRE', 'LUMIERE', 'MERVEILLE', 'NATATION',
      'OPPORTUN', 'PARFAITEMENT', 'QUESTION', 'RACONTER', 'SYMPATHIQUE', 'TELEPHONE', 'ULTIMATUM', 'VACANCES'
    ]
  },
  de: {
    easy: [
      'HAUS', 'AUTO', 'BLUME', 'FREUND', 'GELB', 'HAUT', 'INNEN', 'JAHR',
      'KIND', 'LIEBE', 'MUTTER', 'NACHT', 'OBST', 'PFERD', 'QUARK', 'RAD',
      'SOMMER', 'TAG', 'VATER', 'WASSER', 'ZAHL', 'ZUG', 'WEG', 'SAND'
    ],
    normal: [
      'APFEL', 'BALLON', 'COMPUTER', 'DONNERSTAG', 'ELEFANT', 'FREITAG', 'GESCHENK', 'HAUPTSTADT',
      'IMPFUNG', 'JUNGFRAU', 'KARTOFFEL', 'LEUCHTER', 'MONTAG', 'NUSSSCHALE', 'OBSTGARTEN', 'PFERDESTALL',
      'QUARZUHR', 'RADIERGUMMI', 'SONNTAG', 'TASCHENMESSER', 'UNIVERSITAT', 'VORHANG', 'WASSERFALL', 'ZITRONE'
    ],
    hard: [
      'ABENDROT', 'BIBLIOTHEK', 'CHAMPIGNON', 'DONAUDAMPFSCHIFFFAHRTSGESELLSCHAFT', 'EISKUNSTLAUF',
      'FERNSEHGERAT', 'GESCHWINDIGKEIT', 'HAUPTBAHNHOF', 'IMPERFEKTUM', 'JUGENDHERBERGE',
      'KINDERGARTEN', 'LICHTGESCHWINDIGKEIT', 'MENSCHHEIT', 'NICHTSDESTOTROTZ', 'OBSTGEMUSE',
      'PFERDEAPFEL', 'QUERSCHNITT', 'RECHTSANWALT', 'SCHWARZWALDER', 'TELEFONBUCH', 'UNIVERSITAT', 'VERGANGENHEIT'
    ]
  },
  it: {
    easy: [
      'AMO', 'DONO', 'FIORE', 'GATTO', 'LAGO', 'MARE', 'NUVOLA', 'OCCHIO',
      'PANE', 'QUI', 'RISO', 'SALE', 'SERA', 'SOLE', 'TRE', 'UVA',
      'VINO', 'ZAINO', 'ZOPPO', 'ZUCCO', 'ZUFOLO', 'ZUPPA', 'ZUCCHERO', 'ZAINO'
    ],
    normal: [
      'ALBERO', 'BICICLETTA', 'CASA', 'DOLCE', 'FAMIGLIA', 'GIOCO', 'LIBERO', 'MUSICA',
      'NATALE', 'OCCHIALI', 'PALLA', 'QUADRATO', 'REGALO', 'SCARPA', 'TIGRE', 'UCCELLO',
      'VALIGIA', 'ZAINO', 'ZUCCA', 'ARANCIA', 'BOTTONE', 'DIVANO', 'FARFALLA', 'GIRASOLE'
    ],
    hard: [
      'ACQUARIO', 'BIBLIOTECA', 'CALEIDOSCOPIO', 'DISTRUGGERE', 'ELEFANTE', 'FOTOGRAFIA', 'GIOIELLIERE',
      'IMPRENDITORE', 'LAMPADINA', 'MERAVIGLIA', 'OCEANO', 'PALAZZINA', 'QUADERNO', 'RINOCERONTE',
      'SCARABOCCHIO', 'TELESCOPIO', 'UMIDIFICATORE', 'VETERINARIO', 'ZUCCHERIERA', 'ACQUISTO', 'BENVENUTO', 'CAMPANILE'
    ]
  },
  pt: {
    easy: [
      'AMOR', 'BEM', 'CAO', 'DIA', 'ECO', 'FIM', 'GELO', 'HAJA',
      'ILHA', 'JOGO', 'LUA', 'MAL', 'NOVO', 'OLHO', 'PAO', 'QUARTO',
      'REI', 'SAL', 'TEMPO', 'URSO', 'VOO', 'ZUMBIDO', 'XALE', 'ZEBRA'
    ],
    normal: [
      'AMIGO', 'BANANA', 'CACHORRO', 'DENTISTA', 'ELEFANTE', 'FAMILIA', 'GARRAFA', 'HORIZONTE',
      'IGUALDADE', 'JANELA', 'KILO', 'LIVRO', 'MUSICA', 'NATUREZA', 'OCULOS', 'PASSARO',
      'QUARTO', 'RADIO', 'SAPATO', 'TIGRE', 'URGENTE', 'VIAGEM', 'XADREZ', 'ZANGADO'
    ],
    hard: [
      'AMANHA', 'BIBLIOTECA', 'CALEIDOSCOPIO', 'DESENVOLVIMENTO', 'ELETRICIDADE', 'FOTOGRAFIA', 'GARANTIA',
      'HABILIDADE', 'IMPRESSIONANTE', 'JORNALISMO', 'KILOMETRO', 'LUMINOSIDADE', 'MISTERIOSO', 'OPORTUNIDADE',
      'PESQUISADOR', 'QUALIDADE', 'RESPONSABILIDADE', 'SIMPATIA', 'TECLADO', 'ULTIMAMENTE', 'VETERINARIO', 'ZOOLOGICO'
    ]
  },
  'pt-BR': {
    easy: [
      'AMOR', 'BEM', 'CAO', 'DIA', 'ECO', 'FIM', 'GELO', 'HAJA',
      'ILHA', 'JOGO', 'LUA', 'MAL', 'NOVO', 'OLHO', 'PAO', 'QUARTO',
      'REI', 'SAL', 'TEMPO', 'URSO', 'VOO', 'ZUMBIDO', 'XALE', 'ZEBRA'
    ],
    normal: [
      'AMIGO', 'BANANA', 'CACHORRO', 'DENTISTA', 'ELEFANTE', 'FAMILIA', 'GARRAFA', 'HORIZONTE',
      'IGUALDADE', 'JANELA', 'KILO', 'LIVRO', 'MUSICA', 'NATUREZA', 'OCULOS', 'PASSARO',
      'QUARTO', 'RADIO', 'SAPATO', 'TIGRE', 'URGENTE', 'VIAGEM', 'XADREZ', 'ZANGADO'
    ],
    hard: [
      'AMANHA', 'BIBLIOTECA', 'CALEIDOSCOPIO', 'DESENVOLVIMENTO', 'ELETRICIDADE', 'FOTOGRAFIA', 'GARANTIA',
      'HABILIDADE', 'IMPRESSIONANTE', 'JORNALISMO', 'QUILOMETRO', 'LUMINOSIDADE', 'MISTERIOSO', 'OPORTUNIDADE',
      'PESQUISADOR', 'QUALIDADE', 'RESPONSABILIDADE', 'SIMPATIA', 'TECLADO', 'ULTIMAMENTE', 'VETERINARIO', 'ZOOLOGICO'
    ]
  },
  'pt-PT': {
    easy: [
      'AMOR', 'BEM', 'CAO', 'DIA', 'ECO', 'FIM', 'GELO', 'HAJA',
      'ILHA', 'JOGO', 'LUA', 'MAL', 'NOVO', 'OLHO', 'PAO', 'QUARTO',
      'REI', 'SAL', 'TEMPO', 'URSO', 'VOO', 'ZUMBIDO', 'XALE', 'ZEBRA'
    ],
    normal: [
      'AMIGO', 'BANANA', 'CACHORRO', 'DENTISTA', 'ELEFANTE', 'FAMILIA', 'GARRAFA', 'HORIZONTE',
      'IGUALDADE', 'JANELA', 'KILO', 'LIVRO', 'MUSICA', 'NATUREZA', 'OCULOS', 'PASSARO',
      'QUARTO', 'RADIO', 'SAPATO', 'TIGRE', 'URGENTE', 'VIAGEM', 'XADREZ', 'ZANGADO'
    ],
    hard: [
      'AMANHA', 'BIBLIOTECA', 'CALEIDOSCOPIO', 'DESENVOLVIMENTO', 'ELECTRICIDADE', 'FOTOGRAFIA', 'GARANTIA',
      'HABILIDADE', 'IMPRESSIONANTE', 'JORNALISMO', 'QUILOMETRO', 'LUMINOSIDADE', 'MISTERIOSO', 'OPORTUNIDADE',
      'PESQUISADOR', 'QUALIDADE', 'RESPONSABILIDADE', 'SIMPATIA', 'TECLADO', 'ULTIMAMENTE', 'VETERINARIO', 'ZOOLOGICO'
    ]
  }
};
